"""Initial schema with social models

Revision ID: efe1acf4d45f
Revises:
Create Date: 2026-06-17 14:56:52.779532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe1acf4d45f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('decks',
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('deck_id')
    )
    op.create_table('follows',
    sa.Column('follow_id', sa.Uuid(), nullable=False),
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('following_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follow_id'),
    sa.UniqueConstraint('follower_id', 'following_id')
    )
    op.create_table('cards',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('front_text', sa.Text(), nullable=False),
    sa.Column('back_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.deck_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('review_logs',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('grade_submitted', sa.String(length=10), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('current_interval_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('review_logs')
    op.drop_table('cards')
    op.drop_table('follows')
    op.drop_table('decks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
